#  Template NodeJS build

#  This template allows you to validate your NodeJS code.
#  The workflow allows running tests and code linting on the default branch.

image: node:16

pipelines:
  branches:
    main:
      - step:
          name: deploy heroku testcrmvideocall
          caches:
            - node
          script:
            - git fetch --all --unshallow
            - git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git
    master:
      - step:
          name: deploy heroku servicehubcrmvideocall
          caches:
            - node
          script:
            - git fetch --all --unshallow
            - git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME_PRO.git
